spring:
  application:
    name: xfsw-web-fe-gateway
    
server:
  port: 8101

zuul:
  routes:
    api-a:
      path: /entry/**
      url: http://localhost:8201
    api-b:
      path: /api-b/**
      serviceId: service-feign
    api-c:
      path: /api-c/**
      url: http://www.baidu.com
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8001/eureka/
      
security:   
  user:  
    name: xfsw #eureka 用户名  
    password: xfsw-eureka #eureka 密码  